package com.ubbcluj.authentication.config;

import com.ubbcluj.authentication.dto.ErrorResponseDto;
import com.ubbcluj.authentication.exception.*;
import org.springframework.core.Ordered;
import org.springframework.core.annotation.Order;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.http.converter.HttpMessageNotReadableException;
import org.springframework.web.bind.MissingRequestCookieException;
import org.springframework.web.bind.MissingRequestHeaderException;
import org.springframework.web.bind.MissingRequestValueException;
import org.springframework.web.bind.annotation.ControllerAdvice;
import org.springframework.web.bind.annotation.ExceptionHandler;

import static com.ubbcluj.authentication.exception.ServiceErrorCodes.INTERNAL_SERVER_ERROR;


@Order(Ordered.HIGHEST_PRECEDENCE)
@ControllerAdvice
public class RestExceptionHandler {

    /**
     * Handles all {@link Throwable}s that aren't caught by more specific handlers.
     * <b>IMPORTANT:</b> This is only the last resort to prevent the exposure of error information generated by Spring Boot. The error message
     * uses a generic internal server error messages.
     */
    @ExceptionHandler({Throwable.class})
    public ResponseEntity<ErrorResponseDto> handleThrowable(Throwable throwable) {
        return ResponseEntity.internalServerError().body(createErrorResponse());
    }

    /**
     * Handles Missing request exceptions.
     */
    @ExceptionHandler({
            HttpMessageNotReadableException.class,
            MissingRequestHeaderException.class,
            MissingRequestValueException.class,
            MissingRequestCookieException.class
    })
    public ResponseEntity<Object> handleRequestException() {
        return ResponseEntity.badRequest().build();
    }

    /**
     * Handles {@link AuthenticationException}s
     */
    @ExceptionHandler({AuthenticationException.class})
    public ResponseEntity<ErrorResponseDto> handleException(AuthenticationException accountNotFoundException) {
        return new ResponseEntity<>(createErrorResponse(accountNotFoundException), HttpStatus.NOT_FOUND);
    }

    /**
     * Handles {@link ConflictException}s.
     */
    @ExceptionHandler({ConflictException.class})
    public ResponseEntity<ErrorResponseDto> handleException(ConflictException conflictException) {
        return new ResponseEntity<>(createErrorResponse(conflictException), HttpStatus.CONFLICT);
    }

    /**
     * Handles {@link EntityNotFoundException}s.
     */
    @ExceptionHandler({EntityNotFoundException.class})
    public ResponseEntity<ErrorResponseDto> handleException(EntityNotFoundException entityNotFoundException) {
        return new ResponseEntity<>(createErrorResponse(entityNotFoundException), HttpStatus.NOT_FOUND);
    }

    /**
     * Handles {@link RequestNotValidException}s.
     */
    @ExceptionHandler(RequestNotValidException.class)
    public ResponseEntity<ErrorResponseDto> handleException(RequestNotValidException requestNotValidException) {
        return new ResponseEntity<>(createErrorResponse(requestNotValidException), HttpStatus.BAD_REQUEST);
    }

    /**
     * Creates a {@link ErrorResponseDto} from parameters from the {@link BaseException}.
     *
     * @param baseException containing the error parameters
     * @return the {@link ErrorResponseDto}
     */
    private ErrorResponseDto createErrorResponse(BaseException baseException) {
        return new ErrorResponseDto(baseException.getErrorCode(), baseException.getErrorName(), baseException.getErrorMessage());
    }

    /**
     * Creates a {@link ErrorResponseDto} for the given request and throwable. The result is a generic HTTP 500 error response.
     *
     * @return the error response
     */
    protected ErrorResponseDto createErrorResponse() {
        return new ErrorResponseDto(INTERNAL_SERVER_ERROR.errorCode(), INTERNAL_SERVER_ERROR.errorName(), INTERNAL_SERVER_ERROR.errorMessage());
    }
}
